import { useEffect, useRef, useState } from "react"
import type { ScoreResponse } from "../lib/api"
import { getVoiceUrl } from "../lib/api"

// ── Design tokens ─────────────────────────────────────────────────────────────

const T = {
  bg:        "#FFFFFF",
  header:    "#1C2B3A",
  border:    "#E8EDF2",
  sectionBg: "#F8FAFB",
  text:      "#0F1923",
  sub:       "#5A6B7A",
  muted:     "#9AABB8",
  orange:    "#FF9900",
  green:     "#16A34A",
  amber:     "#D97706",
  red:       "#DC2626",
  drawerW:   380,
  collapseW: 52,
}

// ── Verdict helpers ───────────────────────────────────────────────────────────

function verdictData(s: number) {
  if (s >= 75) return { label: "BUY",   text: "Buy with confidence",  sub: "Strong sustainability record",  accent: "#16A34A", heroFrom: "#D1FAE5", heroTo: "#ECFDF5" }
  if (s >= 60) return { label: "BUY",   text: "Good eco choice",      sub: "Above-average sustainability",  accent: "#2563EB", heroFrom: "#DBEAFE", heroTo: "#EFF6FF" }
  if (s >= 45) return { label: "PAUSE", text: "Consider alternatives", sub: "Some environmental concerns",  accent: "#D97706", heroFrom: "#FEF3C7", heroTo: "#FFFBEB" }
  return             { label: "SKIP",  text: "Skip if possible",      sub: "High environmental impact",    accent: "#DC2626", heroFrom: "#FEE2E2", heroTo: "#FFF5F5" }
}

function barColor(s: number) {
  if (s >= 65) return "#16A34A"
  if (s >= 40) return "#D97706"
  return "#DC2626"
}

function estimateCO2(score: number) {
  const kg = +(2 + (100 - score) * 0.12).toFixed(1)
  return { kg, km: Math.round(kg / 0.12) }
}

function confidenceDot(c: string) {
  if (c === "High")   return "#16A34A"
  if (c === "Medium") return "#D97706"
  return "#9CA3AF"
}

// ── Dimension metadata ────────────────────────────────────────────────────────

const DIM_META: Record<string, { label: string; icon: string; weight: string; description: string; goodMeans: string; badMeans: string; learnUrl: string }> = {
  carbon:         { label: "Carbon Footprint", icon: "🌫️", weight: "30%", description: "Estimated CO₂ from manufacturing & shipping based on country of origin, product category, and material density.", goodMeans: "Made locally or from low-carbon materials (wood, recycled content)", badMeans: "Manufactured far away, heavy materials, energy-intensive category (electronics)", learnUrl: "https://www.epa.gov/ghgemissions/overview-greenhouse-gases" },
  brand_ethics:   { label: "Brand Ethics",     icon: "🤝", weight: "25%", description: "How responsibly the brand operates — worker welfare, transparency, known controversies sourced via AI web research.", goodMeans: "B Corp certified, Fair Trade, transparent supply chain, no major controversies", badMeans: "Known labor violations, greenwashing history, poor transparency rating", learnUrl: "https://goodonyou.eco" },
  packaging:      { label: "Packaging",        icon: "📦", weight: "20%", description: "Waste generated by the product's packaging, inferred from brand claims, product type, and Amazon review sentiment.", goodMeans: "Minimal packaging, recycled materials, FSC certified, Frustration-Free Packaging", badMeans: "Excessive plastic, 'box within a box', single-use materials flagged in reviews", learnUrl: "https://www.amazon.com/b?node=5521637011" },
  certifications: { label: "Certifications",  icon: "🏆", weight: "15%", description: "Third-party verified sustainability certifications found in the product listing or brand's public page.", goodMeans: "USDA Organic, Fair Trade, Energy Star, FSC, Rainforest Alliance, EPA Safer Choice", badMeans: "No certifications found — score based on AI inference only", learnUrl: "https://www.aboutamazon.com/news/sustainability/what-is-climate-pledge-friendly" },
  durability:     { label: "Durability",       icon: "⚙️", weight: "10%", description: "How long the product is designed to last, based on category baseline, right-to-repair considerations, and review signals.", goodMeans: "Long lifespan, repairable, timeless design (cast iron, quality tools, classic apparel)", badMeans: "Fast-fashion risk, disposable category, reviews mention early failure or breakage", learnUrl: "https://repair.eu" },
}

const SOURCE_URLS: Record<string, string> = {
  "Open Food Facts": "https://openfoodfacts.org",
  "GoodOnYou":       "https://goodonyou.eco",
  "Gemini AI":       "https://deepmind.google/technologies/gemini/",
  "Amazon Listing":  "https://www.amazon.com",
  "EPA":             "https://www.epa.gov",
  "B Corp":          "https://bcorporation.net",
  "Energy Star":     "https://www.energystar.gov",
}

// ── Inline SVG icons ──────────────────────────────────────────────────────────

const LeafIcon = () => (
  <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
    <path d="M2 14C4 14 14 12 14 2C14 2 6 2 4 8C3.2 10 2.8 12 2 14Z" fill="#4ADE80" opacity="0.9"/>
    <path d="M2 14C4 10 6 7 10 5" stroke="#16A34A" strokeWidth="1.2" strokeLinecap="round"/>
  </svg>
)

const ChevronDown = ({ size = 14, color = T.muted, rotated = false }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none"
    style={{ transform: rotated ? "rotate(180deg)" : "none", transition: "transform 0.25s ease", flexShrink: 0 }}>
    <path d="M6 9l6 6 6-6" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)

const ChevronLeft = ({ size = 14, color = "#fff" }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
    <path d="M15 18l-6-6 6-6" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)

const ChevronRight = ({ size = 14, color = "#fff" }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
    <path d="M9 18l6-6-6-6" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)

const CloseIcon = ({ size = 12, color = T.muted }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
    <path d="M18 6L6 18M6 6l12 12" stroke={color} strokeWidth="2" strokeLinecap="round"/>
  </svg>
)

// ── Small score badge for comparison grid ────────────────────────────────────

function CompareScoreBadge({ s }: { s: number }) {
  const bg = s >= 65 ? "#16A34A" : s >= 40 ? "#D97706" : "#DC2626"
  return (
    <div style={{
      width: 32, height: 32, borderRadius: "50%",
      background: bg, display: "flex", alignItems: "center", justifyContent: "center",
      boxShadow: `0 2px 6px ${bg}50`
    }}>
      <span style={{ fontSize: 11, fontWeight: 900, color: "#fff", lineHeight: 1 }}>{s}</span>
    </div>
  )
}

// ── Animated score ring ───────────────────────────────────────────────────────

function ScoreRing({ score }: { score: number }) {
  const size = 92
  const r    = size * 0.38
  const circ = 2 * Math.PI * r
  const sw   = size * 0.085
  const [offset, setOffset]   = useState(circ)
  const [display, setDisplay] = useState(0)

  useEffect(() => {
    const t0 = performance.now(), dur = 1400
    let raf: number
    const tick = (now: number) => {
      const p = Math.min(1, (now - t0) / dur)
      const e = 1 - Math.pow(1 - p, 3)
      setDisplay(Math.round(score * e))
      setOffset(circ * (1 - (score / 100) * e))
      if (p < 1) raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [score])

  return (
    <div style={{ position: "relative", width: size, height: size, flexShrink: 0 }}>
      <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} style={{ transform: "rotate(-90deg)" }}>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="rgba(0,0,0,0.1)" strokeWidth={sw}/>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="rgba(0,0,0,0.75)" strokeWidth={sw}
          strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round"
          style={{ transition: "stroke-dashoffset 0.05s" }}
        />
      </svg>
      <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
        <span style={{ fontSize: 28, fontWeight: 900, color: "rgba(0,0,0,0.85)", lineHeight: 1, letterSpacing: "-1.5px" }}>{display}</span>
        <span style={{ fontSize: 11, color: "rgba(0,0,0,0.5)", fontWeight: 600 }}>/ 100</span>
      </div>
    </div>
  )
}

// ── Dimension bar (with drill-down) ──────────────────────────────────────────

function DimBar({ dimKey, score, index, isWorst }: { dimKey: string; score: number; index: number; isWorst: boolean }) {
  const [width,    setWidth]    = useState(0)
  const [expanded, setExpanded] = useState(false)
  const color = barColor(score)
  const meta  = DIM_META[dimKey] ?? { label: dimKey, icon: "•", weight: "", description: "", goodMeans: "", badMeans: "No data available", learnUrl: "" }

  useEffect(() => {
    const t = setTimeout(() => setWidth(score), 80 + index * 60)
    return () => clearTimeout(t)
  }, [score, index])

  return (
    <div style={{
      marginBottom: 2,
      borderRadius: 10,
      ...(isWorst ? { background: `${color}0A`, border: `1px solid ${color}25`, padding: "8px 10px", margin: "0 -2px 6px" } : { padding: "5px 2px" })
    }}>
      <button
        onClick={() => setExpanded(v => !v)}
        style={{
          width: "100%", background: "none", border: "none", cursor: "pointer",
          display: "flex", alignItems: "center", gap: 10, fontFamily: "inherit", padding: 0
        }}
      >
        <span style={{ fontSize: 15, width: 20, textAlign: "center", flexShrink: 0, lineHeight: 1 }}>{meta.icon}</span>
        <span style={{
          fontSize: 13, color: T.text, width: 110, flexShrink: 0,
          textAlign: "left", fontWeight: isWorst ? 600 : 400,
          whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis"
        }}>
          {meta.label}
          {isWorst && <span style={{ fontSize: 9, color, marginLeft: 5, fontWeight: 700 }}>↓ Lowest</span>}
        </span>
        <div style={{ flex: 1, background: "#EEF2F6", borderRadius: 99, height: 6, overflow: "hidden" }}>
          <div style={{
            width: `${width}%`, height: "100%", borderRadius: 99,
            background: `linear-gradient(90deg, ${color}70, ${color})`,
            transition: "width 0.8s cubic-bezier(0.34,1.1,0.64,1)"
          }}/>
        </div>
        <span style={{ fontSize: 13, fontWeight: 800, color, width: 26, textAlign: "right", flexShrink: 0 }}>
          {Math.round(score)}
        </span>
        <span style={{ fontSize: 10, color: T.muted, flexShrink: 0 }}>{meta.weight}</span>
        <ChevronDown size={12} color={T.muted} rotated={expanded} />
      </button>

      {/* Per-dim drill-down */}
      <div style={{ overflow: "hidden", maxHeight: expanded ? 300 : 0, transition: "max-height 0.3s ease" }}>
        <div style={{
          marginTop: 10, padding: "10px 12px",
          background: "#fff", borderRadius: 8, border: "1px solid #E8EDF2"
        }}>
          <p style={{ margin: "0 0 8px", fontSize: 12, color: T.sub, lineHeight: 1.65 }}>{meta.description}</p>
          <div style={{ display: "flex", gap: 6, marginBottom: 8 }}>
            <div style={{ flex: 1, background: "#F0FDF4", borderRadius: 6, padding: "6px 8px", border: "1px solid #BBF7D0" }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: T.green, marginBottom: 3 }}>✓ Good if</div>
              <div style={{ fontSize: 11, color: "#166534", lineHeight: 1.5 }}>{meta.goodMeans}</div>
            </div>
            <div style={{ flex: 1, background: "#FFF5F5", borderRadius: 6, padding: "6px 8px", border: "1px solid #FECACA" }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: T.red, marginBottom: 3 }}>✕ Bad if</div>
              <div style={{ fontSize: 11, color: "#991B1B", lineHeight: 1.5 }}>{meta.badMeans}</div>
            </div>
          </div>
          <a href={meta.learnUrl} target="_blank" rel="noreferrer"
            style={{ fontSize: 11, color: "#0369A1", fontWeight: 600, textDecoration: "none" }}>
            Learn more ↗
          </a>
        </div>
      </div>
    </div>
  )
}

// ── Collapsible section wrapper ───────────────────────────────────────────────

function Section({ title, badge, children, defaultOpen = true }: {
  title: string; badge?: string | number; children: React.ReactNode; defaultOpen?: boolean
}) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div style={{ borderBottom: `1px solid ${T.border}` }}>
      {/* Section header — full-width clickable */}
      <button
        onClick={() => setOpen(v => !v)}
        style={{
          width: "100%", background: "none", border: "none", cursor: "pointer",
          display: "flex", alignItems: "center", justifyContent: "space-between",
          padding: "13px 16px", fontFamily: "inherit",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: T.muted, textTransform: "uppercase", letterSpacing: "0.9px" }}>
            {title}
          </span>
          {badge !== undefined && (
            <span style={{
              fontSize: 10, background: "#EEF2F6", color: T.sub,
              borderRadius: 99, padding: "1px 7px", fontWeight: 700
            }}>{badge}</span>
          )}
        </div>
        <ChevronDown size={14} color={T.muted} rotated={open} />
      </button>

      {/* Animated body */}
      <div style={{ overflow: "hidden", maxHeight: open ? 2000 : 0, transition: "max-height 0.35s cubic-bezier(0.4,0,0.2,1)" }}>
        <div style={{ padding: "0 16px 16px" }}>
          {children}
        </div>
      </div>
    </div>
  )
}

// ── Collapsed strip ───────────────────────────────────────────────────────────

function CollapsedStrip({ score, accent, onExpand }: {
  score: number; accent: string; onExpand: () => void
}) {
  return (
    <div style={{
      position: "absolute", inset: 0, display: "flex", flexDirection: "column",
      alignItems: "center", justifyContent: "space-between",
      padding: "16px 0", background: T.bg, cursor: "default"
    }}>
      {/* Top: logo */}
      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
        <LeafIcon />
        <span style={{ fontSize: 8, fontWeight: 800, color: T.orange, textTransform: "uppercase", letterSpacing: "0.5px" }}>
          Eco
        </span>
      </div>

      {/* Middle: score */}
      <div style={{
        display: "flex", flexDirection: "column", alignItems: "center", gap: 4,
        padding: "12px 8px", borderRadius: 12,
        background: `${accent}15`, border: `2px solid ${accent}40`
      }}>
        <span style={{ fontSize: 22, fontWeight: 900, color: accent, lineHeight: 1, letterSpacing: "-1px" }}>
          {score}
        </span>
        <span style={{ fontSize: 8, color: accent, fontWeight: 700, opacity: 0.7 }}>/100</span>
      </div>

      {/* Bottom: expand button */}
      <button
        onClick={onExpand}
        title="Expand EcoLens"
        style={{
          background: T.header, border: "none", borderRadius: 10, cursor: "pointer",
          padding: "10px 6px", display: "flex", flexDirection: "column", alignItems: "center",
          gap: 4
        }}
      >
        <ChevronLeft size={13} color="#fff" />
        <span style={{ fontSize: 8, color: "rgba(255,255,255,0.6)", fontWeight: 600, writingMode: "vertical-rl", transform: "rotate(180deg)" }}>
          Expand
        </span>
      </button>
    </div>
  )
}

// ── Main ScoreCard drawer ─────────────────────────────────────────────────────

interface Props { score: ScoreResponse; onDismiss: () => void }

export function ScoreCard({ score, onDismiss }: Props) {
  const [collapsed,  setCollapsed]  = useState(false)
  const [decision,   setDecision]   = useState<"idle" | "skipped">("idle")
  const [voiceState, setVoiceState] = useState<"idle" | "loading" | "playing" | "error">("idle")
  const audioRef = useRef<HTMLAudioElement | null>(null)

  const verdict = verdictData(score.score)
  const co2     = estimateCO2(score.score)

  const dims = [
    { key: "carbon",         val: score.dimensions.carbon         },
    { key: "brand_ethics",   val: score.dimensions.brand_ethics   },
    { key: "packaging",      val: score.dimensions.packaging       },
    { key: "certifications", val: score.dimensions.certifications  },
    { key: "durability",     val: score.dimensions.durability      },
  ].sort((a, b) => a.val - b.val)

  const worstKey = dims[0].key
  const worstVal = dims[0].val

  async function handleListen() {
    if (voiceState === "loading") return
    if (voiceState === "playing") {
      audioRef.current?.pause(); setVoiceState("idle"); return
    }
    setVoiceState("loading")
    try {
      const url   = await getVoiceUrl(score.asin)
      const audio = new Audio(url)
      audioRef.current = audio
      audio.onended = () => setVoiceState("idle")
      await audio.play()
      setVoiceState("playing")
    } catch {
      setVoiceState("error")
      setTimeout(() => setVoiceState("idle"), 2500)
    }
  }

  async function handleSkip() {
    setDecision("skipped")
    try {
      const stored = await chrome.storage.local.get(["co2_avoided_kg", "auth_token"])
      await chrome.storage.local.set({ co2_avoided_kg: ((stored.co2_avoided_kg as number) || 0) + co2.kg })
      chrome.runtime.sendMessage({ type: "RECORD_DECISION", payload: { asin: score.asin, decision: "skip", co2_kg: co2.kg }, token: stored.auth_token || null })
    } catch {}
    setTimeout(() => setDecision(null), 2600)
  }

  async function handleBuy() {
    try {
      const token = await chrome.storage.local.get("auth_token").then(r => r.auth_token)
      chrome.runtime.sendMessage({ type: "RECORD_DECISION", payload: { asin: score.asin, decision: "buy", co2_kg: 0 }, token: token || null })
    } catch {}
    setCollapsed(true)
  }

  return (
    <div style={{
      position: "fixed", top: 0, right: 0, bottom: 0,
      width: collapsed ? T.collapseW : T.drawerW,
      zIndex: 2147483647,
      background: T.bg,
      boxShadow: "-6px 0 40px rgba(0,0,0,0.16), -1px 0 0 rgba(0,0,0,0.06)",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif",
      transition: "width 0.32s cubic-bezier(0.22,1,0.36,1)",
      overflow: "hidden",
      display: "flex",
      flexDirection: "column",
    }}>

      {/* ── Collapsed strip ─────────────────────────────────────────────────── */}
      <div style={{
        position: "absolute", inset: 0,
        opacity: collapsed ? 1 : 0,
        pointerEvents: collapsed ? "auto" : "none",
        transition: "opacity 0.18s ease",
        zIndex: 2
      }}>
        <CollapsedStrip score={score.score} accent={verdict.accent} onExpand={() => setCollapsed(false)} />
      </div>

      {/* ── Expanded panel ──────────────────────────────────────────────────── */}
      <div style={{
        opacity: collapsed ? 0 : 1,
        pointerEvents: collapsed ? "none" : "auto",
        transition: "opacity 0.18s ease",
        display: "flex", flexDirection: "column", height: "100%",
        minWidth: T.drawerW
      }}>

        {/* Skip success overlay */}
        {decision === "skipped" && (
          <div style={{
            position: "absolute", inset: 0, zIndex: 20, borderRadius: 0,
            background: "linear-gradient(160deg, #F0FDF4, #DCFCE7)",
            display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
            animation: "ecolens-fade-in 0.3s ease both"
          }}>
            <div style={{ fontSize: 60, lineHeight: 1, marginBottom: 16, animation: "ecolens-score-pop 0.5s cubic-bezier(0.34,1.56,0.64,1) both" }}>🌿</div>
            <div style={{ fontSize: 24, fontWeight: 800, color: "#166534", marginBottom: 8 }}>Nice choice!</div>
            <div style={{ fontSize: 15, fontWeight: 700, color: T.green }}>You avoided ~{co2.kg} kg CO₂</div>
            <div style={{ fontSize: 12, color: "#4B7C5E", marginTop: 6 }}>≈ not driving {co2.km} km</div>
            <div style={{ marginTop: 20, background: "#BBF7D0", borderRadius: 20, padding: "6px 16px", fontSize: 11, color: "#166534", fontWeight: 600 }}>
              Saved to your EcoLens impact log
            </div>
          </div>
        )}

        {/* HEADER */}
        <div style={{
          background: T.header, padding: "0 16px",
          display: "flex", alignItems: "center", justifyContent: "space-between",
          height: 52, flexShrink: 0,
          borderBottom: "1px solid rgba(255,255,255,0.06)"
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <LeafIcon />
            <span style={{ color: T.orange, fontWeight: 800, fontSize: 14, letterSpacing: "0.3px" }}>EcoLens</span>
            {score.cached && (
              <span style={{ fontSize: 9, color: "#FF9900AA", background: "#FF990018", padding: "2px 6px", borderRadius: 4, border: "1px solid #FF990030" }}>cached</span>
            )}
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            {/* Collapse */}
            <button
              onClick={() => setCollapsed(true)}
              title="Collapse drawer"
              style={{
                background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: 8, cursor: "pointer", padding: "6px 8px",
                display: "flex", alignItems: "center", gap: 4
              }}
            >
              <ChevronRight size={12} color="rgba(255,255,255,0.7)" />
              <span style={{ fontSize: 10, color: "rgba(255,255,255,0.55)", fontWeight: 500 }}>Collapse</span>
            </button>
            {/* Close */}
            <button
              onClick={onDismiss}
              title="Close"
              style={{
                background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: 8, cursor: "pointer", padding: "7px 9px",
                display: "flex", alignItems: "center"
              }}
            >
              <CloseIcon size={11} color="rgba(255,255,255,0.7)" />
            </button>
          </div>
        </div>

        {/* VERDICT HERO */}
        <div style={{
          background: `linear-gradient(145deg, ${verdict.heroFrom}, ${verdict.heroTo})`,
          padding: "20px 18px 18px",
          display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12,
          flexShrink: 0,
          borderBottom: `2px solid ${verdict.accent}30`
        }}>
          <div style={{ flex: 1, minWidth: 0 }}>
            {/* Label pill */}
            <div style={{
              display: "inline-flex", alignItems: "center",
              background: `${verdict.accent}22`, border: `1.5px solid ${verdict.accent}55`,
              borderRadius: 20, padding: "3px 10px", marginBottom: 10
            }}>
              <span style={{ fontSize: 10, fontWeight: 900, color: verdict.accent, letterSpacing: "2px" }}>
                {verdict.label}
              </span>
            </div>
            {/* Main verdict */}
            <div style={{ fontSize: 20, fontWeight: 800, color: T.text, lineHeight: 1.2, marginBottom: 4 }}>
              {verdict.text}
            </div>
            <div style={{ fontSize: 13, color: T.sub, marginBottom: 14, lineHeight: 1.4 }}>
              {verdict.sub}
            </div>
            {/* CO₂ chip */}
            <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
              <div style={{
                background: `${verdict.accent}18`, border: `1px solid ${verdict.accent}40`,
                borderRadius: 8, padding: "5px 10px",
                display: "flex", alignItems: "center", gap: 5
              }}>
                <span style={{ fontSize: 12, color: verdict.accent, fontWeight: 700 }}>~{co2.kg} kg CO₂</span>
              </div>
              <span style={{ fontSize: 11, color: T.muted }}>≈ {co2.km} km driving</span>
            </div>
          </div>
          <ScoreRing score={score.score} />
        </div>

        {/* SCROLLABLE BODY */}
        <div style={{ flex: 1, overflowY: "auto", background: T.bg }}>

          {/* Confidence strip */}
          <div style={{
            padding: "10px 16px",
            display: "flex", alignItems: "center", flexWrap: "wrap", gap: 6,
            borderBottom: `1px solid ${T.border}`
          }}>
            <span style={{
              fontSize: 11, fontWeight: 600, padding: "3px 9px", borderRadius: 20,
              background: "#F8FAFB", color: T.sub, border: `1px solid ${T.border}`,
              display: "inline-flex", alignItems: "center", gap: 4
            }}>
              <span style={{ width: 6, height: 6, borderRadius: "50%", background: confidenceDot(score.confidence), display: "inline-block" }}/>
              {score.confidence} confidence
            </span>
            {score.climate_pledge_friendly && (
              <span style={{
                fontSize: 11, fontWeight: 600, padding: "3px 9px", borderRadius: 20,
                background: "#DCFCE7", color: "#166534", border: "1px solid #BBF7D0"
              }}>
                Climate Pledge Friendly
              </span>
            )}
          </div>

          {/* Section: Score Breakdown */}
          <Section title="Score Breakdown" badge={`${dims.length} factors`}>
            <div style={{ paddingTop: 4 }}>
              {dims.map((d, i) => (
                <DimBar key={d.key} dimKey={d.key} score={d.val} index={i} isWorst={i === 0 && d.val < 50}/>
              ))}
            </div>
          </Section>

          {/* Section: Main Concern (only if worst < 50) */}
          {worstVal < 50 && (() => {
            const meta = DIM_META[worstKey] ?? { label: worstKey, icon: "•", badMeans: "" }
            const col  = barColor(worstVal)
            return (
              <Section title="Main Concern">
                <div style={{
                  background: `${col}0A`, border: `1px solid ${col}25`,
                  borderRadius: 10, padding: "12px 14px",
                  display: "flex", alignItems: "flex-start", gap: 10
                }}>
                  <span style={{ fontSize: 20, lineHeight: 1, flexShrink: 0, marginTop: 1 }}>{meta.icon}</span>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 700, color: col, marginBottom: 5 }}>
                      {meta.label} — scored {Math.round(worstVal)}/100
                    </div>
                    <div style={{ fontSize: 12, color: T.sub, lineHeight: 1.6 }}>
                      This is the biggest drag on this product's eco rating. {meta.badMeans}.
                    </div>
                  </div>
                </div>
              </Section>
            )
          })()}

          {/* Section: Compare Similar Products */}
          {score.alternatives.length > 0 && (
            <Section title="Compare Similar" badge={score.alternatives.length}>
              {/* Horizontal scroll row — current product anchor + all alternatives */}
              <div style={{
                display: "flex", gap: 8, overflowX: "auto", paddingBottom: 6,
                scrollbarWidth: "none",
                // Hide webkit scrollbar
              }}>
                {/* Current product card */}
                <div style={{
                  flexShrink: 0, width: 108,
                  background: `${verdict.accent}10`,
                  border: `2px solid ${verdict.accent}50`,
                  borderRadius: 12, padding: "10px 8px",
                  display: "flex", flexDirection: "column", alignItems: "center", gap: 6
                }}>
                  {score.alternatives[0]?.image_url ? (
                    <div style={{ width: 60, height: 60, borderRadius: 8, background: "#f0f0f0", overflow: "hidden", flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center" }}>
                      <div style={{ width: 40, height: 40, borderRadius: "50%", background: `${verdict.accent}20`, border: `2px solid ${verdict.accent}50`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                        <span style={{ fontSize: 13, fontWeight: 900, color: verdict.accent }}>{score.score}</span>
                      </div>
                    </div>
                  ) : (
                    <div style={{ width: 60, height: 60, borderRadius: 8, background: `${verdict.accent}15`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                      <span style={{ fontSize: 18, fontWeight: 900, color: verdict.accent }}>{score.score}</span>
                    </div>
                  )}
                  <div style={{
                    fontSize: 8, fontWeight: 800, letterSpacing: "1px",
                    color: verdict.accent, textTransform: "uppercase", textAlign: "center"
                  }}>
                    This product
                  </div>
                  <CompareScoreBadge s={score.score} />
                </div>

                {/* Alternative cards */}
                {score.alternatives.slice(0, 5).map((alt) => {
                  const delta = alt.score - score.score
                  const isGreener = delta > 3
                  const isWorse   = delta < -3
                  const deltaColor = isGreener ? T.green : isWorse ? T.red : T.amber
                  const deltaText  = delta > 0 ? `+${delta}` : `${delta}`
                  return (
                    <a
                      key={alt.asin}
                      href={`https://www.amazon.com/dp/${alt.asin}`}
                      target="_blank" rel="noreferrer"
                      title={alt.title}
                      style={{
                        flexShrink: 0, width: 108,
                        background: isGreener ? "#F0FDF4" : isWorse ? "#FFF5F5" : "#FAFAFA",
                        border: `1.5px solid ${isGreener ? "#86EFAC" : isWorse ? "#FECACA" : T.border}`,
                        borderRadius: 12, padding: "10px 8px",
                        display: "flex", flexDirection: "column", alignItems: "center", gap: 6,
                        textDecoration: "none", cursor: "pointer",
                        transition: "transform 0.15s ease, box-shadow 0.15s ease"
                      }}
                      onMouseEnter={e => {
                        const el = e.currentTarget as HTMLElement
                        el.style.transform = "translateY(-2px)"
                        el.style.boxShadow = "0 4px 14px rgba(0,0,0,0.1)"
                      }}
                      onMouseLeave={e => {
                        const el = e.currentTarget as HTMLElement
                        el.style.transform = ""; el.style.boxShadow = ""
                      }}
                    >
                      {/* Product image */}
                      <div style={{
                        width: 60, height: 60, borderRadius: 8,
                        background: "#fff", border: `1px solid ${T.border}`,
                        overflow: "hidden", flexShrink: 0,
                        display: "flex", alignItems: "center", justifyContent: "center"
                      }}>
                        {alt.image_url
                          ? <img src={alt.image_url} alt="" style={{ width: "100%", height: "100%", objectFit: "contain" }} />
                          : <span style={{ fontSize: 22, color: T.muted }}>📦</span>
                        }
                      </div>

                      {/* Title */}
                      <div style={{
                        fontSize: 10, color: T.text, fontWeight: 500, lineHeight: 1.3,
                        textAlign: "center", width: "100%",
                        overflow: "hidden", display: "-webkit-box",
                        WebkitLineClamp: 2, WebkitBoxOrient: "vertical"
                      }}>
                        {alt.title}
                      </div>

                      {/* Score + delta row */}
                      <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3, width: "100%" }}>
                        <CompareScoreBadge s={alt.score} />
                        <span style={{
                          fontSize: 9, fontWeight: 700, color: deltaColor,
                          background: `${deltaColor}18`, padding: "1px 6px", borderRadius: 10
                        }}>
                          {deltaText} pts
                        </span>
                      </div>
                    </a>
                  )
                })}
              </div>
              <p style={{ margin: "6px 0 0", fontSize: 10, color: T.muted, lineHeight: 1.5 }}>
                Scores are AI estimates. Click any product to open on Amazon.
              </p>
            </Section>
          )}

          {/* Section: AI Explanation */}
          <Section title="Why This Score" defaultOpen={false}>
            <p style={{ margin: "4px 0 12px", fontSize: 13, color: T.sub, lineHeight: 1.7 }}>
              {score.explanation}
            </p>
            {/* Confidence explanation */}
            <div style={{
              background: T.sectionBg, borderRadius: 8, border: `1px solid ${T.border}`,
              padding: "10px 12px", display: "flex", alignItems: "flex-start", gap: 10
            }}>
              <div style={{ width: 8, height: 8, borderRadius: "50%", flexShrink: 0, marginTop: 4, background: confidenceDot(score.confidence) }}/>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: T.text, marginBottom: 3 }}>{score.confidence} confidence</div>
                <div style={{ fontSize: 12, color: T.sub, lineHeight: 1.55 }}>
                  {{ High: "Multiple databases matched this product. Score combines verified external data + AI analysis.", Medium: "Partial database match. Some dimensions are AI-inferred from product listing details.", Low: "No database match found. Score is based entirely on Gemini AI analysis — treat with caution." }[score.confidence] ?? ""}
                </div>
              </div>
            </div>
          </Section>

          {/* Section: Data Sources */}
          {score.data_sources.length > 0 && (
            <Section title="Data Sources" badge={score.data_sources.length} defaultOpen={false}>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 4 }}>
                {score.data_sources.map((src, i) => {
                  const url = SOURCE_URLS[src]
                  return url ? (
                    <a key={i} href={url} target="_blank" rel="noreferrer" style={{
                      fontSize: 12, background: "#EFF6FF", color: "#1D4ED8",
                      padding: "3px 10px", borderRadius: 20, fontWeight: 600,
                      textDecoration: "none"
                    }}>
                      {src} ↗
                    </a>
                  ) : (
                    <span key={i} style={{
                      fontSize: 12, background: T.sectionBg, color: T.sub,
                      padding: "3px 10px", borderRadius: 20, fontWeight: 500, border: `1px solid ${T.border}`
                    }}>
                      {src}
                    </span>
                  )
                })}
              </div>
              <div style={{ marginTop: 12, paddingTop: 10, borderTop: `1px solid ${T.border}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ fontSize: 11, color: T.muted }}>Scored by EcoLens AI · not financial advice</span>
                <button
                  onClick={() => { try { chrome.runtime.sendMessage({ type: "OPEN_FEEDBACK", asin: score.asin }) } catch {} }}
                  style={{ background: "none", border: "none", fontSize: 11, color: "#0369A1", cursor: "pointer", fontFamily: "inherit", textDecoration: "underline", padding: 0 }}
                >
                  Flag inaccuracy
                </button>
              </div>
            </Section>
          )}

          {/* Bottom spacer */}
          <div style={{ height: 8 }} />
        </div>

        {/* STICKY FOOTER */}
        <div style={{
          flexShrink: 0,
          borderTop: `1px solid ${T.border}`,
          background: "#fff",
          padding: "12px 14px 14px",
        }}>

          {/* ── Primary actions ── */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, marginBottom: 6 }}>

            {/* SKIP */}
            <button
              onClick={handleSkip}
              style={{
                padding: "10px 8px",
                borderRadius: 8, cursor: "pointer", border: "none",
                fontFamily: "inherit", lineHeight: 1.3, textAlign: "center",
                background:
                  score.score < 45 ? "#DC2626"
                  : score.score < 65 ? "#D97706"
                  : "#F1F5F9",
                color: score.score < 65 ? "#fff" : "#94A3B8",
              }}
            >
              <div style={{ fontWeight: 600, fontSize: 13 }}>Skip</div>
              {score.score < 65 && (
                <div style={{ fontSize: 10, fontWeight: 400, opacity: 0.82, marginTop: 2 }}>
                  save ~{co2.kg} kg CO₂
                </div>
              )}
            </button>

            {/* BUY */}
            <button
              onClick={handleBuy}
              style={{
                padding: "10px 8px",
                borderRadius: 8, cursor: "pointer",
                fontFamily: "inherit", fontWeight: 600, fontSize: 13, lineHeight: 1.3,
                background: score.score >= 65 ? "#16A34A" : "#F1F5F9",
                color:      score.score >= 65 ? "#fff"   : "#94A3B8",
                border:     score.score >= 65 ? "none"   : "1px solid #E2E8F0",
              }}
            >
              {score.score >= 65 ? "Buy it" : "Buy anyway"}
            </button>
          </div>

          {/* ── Utility row ── */}
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6 }}>

            {voiceState !== "error" ? (
              <button
                onClick={handleListen}
                disabled={voiceState === "loading"}
                style={{
                  padding: "7px 8px",
                  borderRadius: 7,
                  cursor: voiceState === "loading" ? "default" : "pointer",
                  fontFamily: "inherit", fontWeight: 500, fontSize: 11,
                  background: "transparent",
                  color: voiceState === "playing" ? T.green : T.sub,
                  border: `1px solid ${voiceState === "playing" ? "#86EFAC" : "#E2E8F0"}`,
                }}
              >
                {voiceState === "idle"    && "Listen"}
                {voiceState === "loading" && "Generating…"}
                {voiceState === "playing" && "Stop"}
              </button>
            ) : (
              <div />
            )}

            <a
              href="https://ecolens.app/dashboard"
              target="_blank" rel="noreferrer"
              style={{
                padding: "7px 8px",
                borderRadius: 7,
                fontFamily: "inherit", fontWeight: 500, fontSize: 11,
                background: "transparent", color: T.sub,
                border: "1px solid #E2E8F0",
                textAlign: "center", textDecoration: "none",
                display: "flex", alignItems: "center", justifyContent: "center",
              }}
            >
              My Impact
            </a>
          </div>

        </div>

      </div>
    </div>
  )
}
